name: Build, Scan, and Deploy Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-scan-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: get_sha
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/my-docker-image:latest
            ghcr.io/${{ github.repository }}/my-docker-image:${{ github.run_number }}-${{ env.GIT_SHA }}
          outputs: type=docker,dest=/tmp/my-docker-image.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/my-docker-image:${{ github.run_number }}-${{ env.GIT_SHA }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=sonar-project.properties

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/my-docker-image:latest
            ghcr.io/${{ github.repository }}/my-docker-image:${{ github.run_number }}-${{ env.GIT_SHA }}

      - name: Log out from Docker Registry
        if: always()
        run: docker logout ghcr.io

