name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pull-request-check:
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository code
      - name: Code checkout
        id: code_checkout
        uses: actions/checkout@v4

      # Scan the repo for any sensitive information like secrets etc
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./ # Code repository path
          base: "" # Start scanning from here
          head: ${{ github.head_ref || github.ref_name }}  # Scan commits until here
          extra_args: --only-verified
