name: "Close stale issues and pr"
on:
  schedule:
  - cron: "0 23 * * *"

jobs:
  stale:
    permissions:
        contents: write # only for delete-branch option
        issues: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        days-before-issue-stale: 90
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment else this will be closed in 7 days'
        exempt-issue-labels: 'triaged'
        days-before-issue-close: 7
        close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'

        days-before-pr-stale: 90
        stale-pr-message: 'This PR is stale because it has been open 90 days with no activity. Remove stale label or comment else this will be closed in 7 days'
        days-before-pr-close: -1 # -1 wont close the pull request
